#########################
#                       #
# Discomc configuration #
#                       #
#########################

# if player is not online his permissions is not loaded
# so we need using for offline players vault
# it can happens when command sender is some discord user
# working only with vault plugin
# FOR online players will be used bukkit permissions
useVaultFeaturesForPermissions: ${default.useVaultFeaturesForPermissions}

discord:
  # token of discord bot
  botToken: ${discord.botToken}
  # bot server id
  mainServerID: ${discord.mainServerID}

database:
  # implemented sqlite, postgresql and mysql
  sqlType: ${database.sqlType}
  host: ${database.host}
  name: ${database.name}
  user: ${database.user}
  password: ${database.password}

# function to connect discord and minecraft account
connect:
  enabled: ${connect.enabled}
  # code will be deleted in this time of ticks
  # -1 if disabled
  codeRemovingTime: ${connect.codeRemovingTime}
  maxCodeValue: ${connect.maxCodeValue}
  # message will be deleted in this value of seconds
  # -1 if disabled
  discordMessageDeleteTime: ${connect.discordMessageDeleteTime}

# depends on connect module
# if connect disabled this feature disabled too
# function to disconnect minecraft account and discord account
disconnect:
  enabled: ${disconnect.enabled}
  # confirm disconnect
  # confirm message in messages.properties
  confirm: ${disconnect.confirm}
  # time to confirm disconnect
  # uses only when confirm setting is enabled
  # in ticks
  timeConfirm: ${disconnect.timeConfirm}

# function to share console in specify text channel
console:
  enabled: ${console.enabled}

# chat between discord and minecraft
multiChat:
  enabled: ${multiChat.enabled}
  # discord message convert to minecraft message
  # using this pattern, where {0} - nickname
  # {1} - visible content of message
  minecraftMessagePattern: ${multiChat.minecraftMessagePattern}
  # vault features like prefixes, suffixes and etc
  # working only with vault plugin
  vaultFeatures: ${multiChat.vaultFeatures}

# function to make shortcuts to execute them like default bot commands
# example: !clear - discord command
# all commands needs to be set in shortcuts.json
# or by command /discomc shortcut
# or by shortcut command shortcut in discord
shortcut:
  enabled: ${shortcut.enabled}
  # commands prefix
  commandsPrefix: ${shortcut.commandsPrefix}
  # in this time message will delete
  # count in seconds
  # -1 to disable
  messageDeleteTime: ${shortcut.messageDeleteTime}
  # response will delete in this seconds
  # -1 to disable
  responseDeleteTime: ${shortcut.responseDeleteTime}
  # command will delete in this seconds
  # -1 to disable
  commandDeleteTime: ${shortcut.commandDeleteTime}

# IF YOU DO NOT KNOW WHAT IS THIS VALUES ARE DOING
# DO NOT CHANGE THEM!
advanced:
  # in ticks
  scheduleCommandsTimer: ${advanced.scheduleCommandsTimer}
  # in ticks
  cachedPlayersClearTimer: ${advanced.cachedPlayersClearTimer}
