name: Discomc
version: 1.0
main: space.cubicworld.DiscomcPlugin
author: Jenya705
website: https://github.com/Jenya705/Discomc
commands:
  connect:
    permission: discomc.connect
    description: Command to connect discord and minecraft accounts
permissions:
  discomc.*:
    default: op
    children:
      discomc.connect: true
  discomc.connect:
    default: true