name: Discomc
version: 1.0.0-SNAPSHOT
main: space.cubicworld.DiscomcPlugin
author: Jenya705
website: https://github.com/Jenya705
commands:
  connect:
    description: Command to connect minecraft account and discord account
    permission: discomc.connect
permissions:
  discomc.*:
    default: op
    children:
      discomc.connect: true
  discomc.connect:
    default: true